### ISSUE TITLE
List of Retriable & Permanent error

### ISSUE THREAD

**Issue by vivekkwatra** [rahulrai-in/kafka-retry-pattern#1]
Do you have list of retriable exception & permanent error which can be handle separately if any producer exception come up?

**Comment by rahulrai-in** [comment]
You don't need to handle the errors yourself. The Producer or Consumer will handle the errors themselves unless the error is fatal. You can read the discussion here: https://github.com/confluentinc/confluent-kafka-dotnet/issues/1213
